### ISSUE TITLE
More than 100 sequences of 8 segments failed to run

### ISSUE THREAD

**Issue by wangboioz** [nicfel/CoalRe#9]
I have put 8 segments into Beauti 2, and each segments contain more than 100 sequences, however, BEAST terminated with an error. When I decreased sequences to 25, beast could run with sampling every 1000, but terminated halfway with tips of "moving on". When I only put in 2 segments (HA and NA) with 25 sequences, beast run sucessfully and gived output.  Could someone tell me why this happened and how can I fixed it, Please? Thanks for any expains and advices.

**Comment by jugne** [comment]
Hi, could you share the xml (you can remove the sequences if that is confidential) and what error exactly BEAST outputs?

**Comment by wangboioz** [comment]
Thanks for your reply. Here is my xml file and I paste the error information.[](url)
[9-2-ressortment.zip](https://github.com/nicfel/CoalRe/files/6521928/9-2-ressortment.zip)

Start likelihood: -209907.94827572428 
Writing file 6-2-NA.log
Writing file 5-2-NP_1,2.trees
Writing file 6-2-NA_1,2.trees
Writing file 7-2-M_1,2.trees
Writing file 8-2-NS_1,2.trees
Writing file 1-2-PB2_1,2.trees
Writing file 2-2-PB1_1,2.trees
Writing file 3-2-PA_1,2.trees
Writing file 4-2-HA_1,2.trees
Writing file infile.network.trees
         Sample      posterior     likelihood          prior
              0   -209907.9482   -209722.6048      -185.3433 --
Fatal exception: null
... moving on

**Comment by nicfel** [comment]
I think what causes the error at the moment is that sequences in the different alignments that correspond to each other have different names. I'll try to add a proper error message for the next CoalRe version about this issue. For now, if you remove all the |_NA etc. from all the sequence names in the different alignments, such that for each sequence in every segment alignment, there is a corresponding sequence in all other segment alignment with exactly the same name, things should hopefully work.

**Comment by wangboioz** [comment]
Thank you for the effort you put in solving my ploblem and constructive suggestions that certainly help me. I will try to processing the sequence names according to your advices. In fact, I considered this issuse before, but due to there are different isolate names between HA and NA in example data, corresponding sequence in all other segment alignment with exactly the same name have not been suplemented in this run.

**Comment by wangboioz** [comment]
Owing to your zealous advances, my problem was solved well. Really appreciate your help! @nicfel
